name: Initialize Bitbucket mirror

on:
  push:
    branches:
      - main

jobs:
  sync_to_bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Bitbucket
        run: |
          git config --global user.email "${{ secrets.BITBUCKET_EMAIL }}"
        env:
          BITBUCKET_EMAIL: ${{ secrets.BITBUCKET_EMAIL }}

      - name: Remove shallow update
        run: git fetch --prune --unshallow

      - name: Push to Bitbucket
        run: |
          git remote add bitbucket https://x-token-auth:${{ secrets.BITBUCKET_TOKEN }}@bitbucket.org/rmottainfo/rmottainfo.bitbucket.io.git
          git push --set-upstream bitbucket --all
          git push --set-upstream bitbucket --tags
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
